global:
  domain: bboyleonp.me
  pullPolicy: IfNotPresent

ingress:
  name: ingress-nginx
  namespace: default
  apis:
    ip: 192.168.1.100/32
    hostname: internal.api
    names:
      pool: pool-0
      l2: l2-0
    services:
      home:
        name: home
        ports:
          http: 80
